language: ruby
rvm:
  - 2.3.1
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database mediators_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rake db:setup
  - bundle exec rake
after_success:
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && bundle exec codeclimate-test-reporter"