require_relative 'parsers/mediators'
require_relative 'parsers/practice'
require_relative 'validators/mediators'
require_relative 'processing/spreadsheet'
require_relative 'processing/headings'
require_relative 'app'