apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: family-mediators-api-pdb-staging
  namespace: family-mediators-api-staging
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: family-mediators-api-web-staging
